### ISSUE TITLE
Analyzer does not consistently process methods that take value types by reference

### ISSUE THREAD

**Issue by PathogenDavid** [szehetner/InliningAnalyzer#10]
Off the heels of #9, I've found another quirk around values by reference, this time with parameters:

```csharp
using System;

namespace InliningAnalyzerIgnoresRefReturnMethods
{
    public class Program
    {
        private static int a;
        private static int b;

        private static ref int Select(ref bool which)
            => ref (which ? ref a : ref b);

        private static int Select2(ref bool which)
            => Select(ref which);

        public static void Main(string[] args)
        {
            bool which = true;
            ref int x = ref Select(ref which);
            int y = Select(ref which);
            int z = Select2(ref which);
            Console.WriteLine(x);
            Console.WriteLine(y);
            Console.WriteLine(z);
        }
    }
}
```

(Note that the `which` parameter is passed by reference now.)

If you run the analyzer, none of the calls to `Select` are highlighted:

![image](https://user-images.githubusercontent.com/278957/47861020-d6616800-ddbf-11e8-9eb7-74ea97d724f2.png)

Unlike last time, I did not observe any weirdness involving 32 vs 64 bit or commenting out the `Select2` call.

**Comment by szehetner** [comment]
This is fixed now as well, basically the same fix as for ref return values was missing for ref parameters.

FYI:
While I was checking other variants of ref methods, I found that ref readonly methods are not always highlighted as well. The reason is that the JIT Compiler emits a strange signature for these methods. I think this is a bug, so I have created an issue for that (https://github.com/dotnet/coreclr/issues/20754). Just in case you stumble upon this as well.

**Comment by PathogenDavid** [comment]
Thanks again, and thanks for the warning!

**Comment by szehetner** [comment]
Version 0.7.4 with this fix has been published.

**Comment by PathogenDavid** [comment]
Thanks again, and thanks for fixing the issue in CoreCLR!
